# -*- coding: utf-8 -*-
"""Questão_2_Letra_D.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TwHkdisZokRpT-FdwE08bZKx5W5XSfIb
"""

def conversao(hora, minuto, segundo, conversao_1, conversao_2, calculo):
  return hora, minuto, segundo, conversao_1, conversao_2, calculo

def main():  
  hora = int(input('Digite um valor para hora: '))
  minuto = int(input('Digite um valor para minuto: '))
  segundo = int(input('Digite um valor para segundo: '))
  conversao_1 = (hora * 3600)
  conversao_2 = (minuto * 60)
  calculo = (conversao_1 + conversao_2 + segundo)
  print(f'Passou {calculo:.0f} segundos no total desde a última meia-noite até a hora lida.')

if __name__=='__main__':
  main()