# -*- coding: utf-8 -*-
"""Questão_2_Letra_E.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ufBJy040TcPy9UaV9uiw-ikxTaHuArgJ
"""

def casa(a, b, c, d, e, f):
  return a, b, c, d, e, f

def main():  
  L = float(input('Digite o valor da largura: '))
  C = float(input('Digite o valor do comprimento: '))
  A = float(input('Digite o valor da altura: '))
  area_piso = (L * C)
  volume_sala = (L * C * A)
  area_parede = (2 * A * L + 2 * A * C)
  print(f'A área do piso da sala é: {area_piso:.0f} m²')
  print(f'O volume da sala é: {volume_sala:.0f} m³')
  print(f'A área das paredes da sala é: {area_parede} m²')

if __name__=='__main__':
  main()