# -*- coding: utf-8 -*-
"""questão_02_Letra_A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lV2U6Q09nfFiOC6h5MpbsmY6NAIcevrC
"""

def data(dia, mes, ano):
  return dia, mes, ano

def main():  
  dia = int(input('Digite o dia: '))
  mes = int(input('Digite o mês: '))
  ano = int(input('Digite o ano: '))
  print(f'{dia}/{mes}/{ano}')

if __name__=='__main__':
  main()