# -*- coding: utf-8 -*-
"""remota_02_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OftYL5ED2sXP3PYOn9hvg1kGiLRMBtk8
"""

def caracteres(a):
  return len(a)
  
def main():
  nome = str(input('Escreve seu nome: ')).strip()
  name = caracteres(nome)
  print(f'Seu nome tem {name} caracteres.') 

if __name__=='__main__':
  main()