# -*- coding: utf-8 -*-
"""remota_02_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13WcGB00GBAkZUa8l7z1gHiNpC79WcK4Q
"""

def a_vista(x):
  return x - (x * (9 / 100))

def vezes_5(y):
  return y / 5 

def vezes_10(z):
  return (z + (z * (17 / 100))) / 10 

def main():
  produto = float(input('Qual o valor do produto? R$ '))
  vista = a_vista(produto)
  prestacao_1 = vezes_5(produto)
  prestacao_2 = vezes_10(produto)
  print(f'Valor para pagamento à vista, com desconto de 9% será de R${vista:0.2f} reais.')
  print(f'Valor da prestação para pagamento em 5 vezes, sem desconto nem juros fica por R${prestacao_1:0.2f} reais.')
  print(f'Valor da prestação para pagamento em 10 vezes, com 17% de juros fica por R${prestacao_2:0.2f} reais.')

if __name__=='__main__':
  main()